### ISSUE TITLE
Bugs 1.12.2 

### ISSUE THREAD

**Issue by ghost** [sb2bg/CustomDeathMessages#16] opened 2023-06-23 16:18 UTC
if player sometime after /kill it says default vanilla message 'Player died'
if i have off  enable-item-on-hover: true it caused after kill player player died by player with kill-weapon
folia dont supported.

**Comment by sb2bg** [comment] 2023-09-25 07:01
Duplicate of closed issues #15 and #13

**Closed as completed by sb2bg** 2023-09-25 07:01 UTC
Labels: bug, duplicate
